### ISSUE TITLE
Minimum Launch Requirements

### ISSUE THREAD

**Issue by thisislawatts** [southlondonmakerspace/wordpress-theme#1]
- [x] Individual post/page template with hero image
- [x] Post comments

**Comment by thisislawatts** [comment]
@unknowndomain 
![question-cat](https://cloud.githubusercontent.com/assets/472589/12276627/b10ec78c-b96e-11e5-9f98-1196810c7668.jpg)

**Comment by thisislawatts** [comment]
Hey @Tomnewsom , 

I was looking at how the Discourse comments might work/appear within the new [theme](http://slms.wpengine.com)
I don't know how far this had got in the existing site as I've not got a login for that WordPress install at the moment.

Is there any chance you'd be able to provide some of the following information from the Discourse installation, so I could start testing it out?

![screenshot 2016-01-12 at 22 56 52](https://cloud.githubusercontent.com/assets/472589/12279584/d815e264-b97f-11e5-84fb-b9a45e20a5ec.png)

**Comment by Tomnewsom** [comment]
Hi Luke

API Key: 41e0002aa83dc022468cb7ec4017fde72bee1efaafcfd5855d7e2908609e2a1e
Username: Makerspace

I've also granted you Admin access on Discourse in case you need to poke
around.

**Comment by thisislawatts** [comment]
Thanks Tom, much appreciated.
