### ISSUE TITLE
New logo needs to be put into site

### ISSUE THREAD

**Issue by unknowndomain** [southlondonmakerspace/wordpress-theme#12]

**Comment by thisislawatts** [comment]
I'll need some kind of source file to work from here. 

Guessing this wasn't the final version..
![](https://discourse.southlondonmakerspace.org/uploads/default/original/2X/4/4baae279b7cbadb9ec24e0862a87a32690f1ed25.png)
https://discourse.southlondonmakerspace.org/t/makerspace-logo-brand/1914/126

**Comment by Tomnewsom** [comment]
https://discourse.southlondonmakerspace.org/uploads/default/original/2X/6/664489c66d757462d323968d4bd6a4c25705116c.png

**Comment by thisislawatts** [comment]
Can I haz SVG to counter hirez screenz?
