### ISSUE TITLE
Line length on Pages

### ISSUE THREAD

**Issue by unknowndomain** [southlondonmakerspace/wordpress-theme#18]
![screen shot 2016-05-26 at 10 51 35](https://cloud.githubusercontent.com/assets/147143/15570820/d8d32a6c-232f-11e6-99a0-f3cf3bcd6bc2.png)

**Comment by thisislawatts** [comment]
![screenshot 2016-05-26 at 16 26 15](https://cloud.githubusercontent.com/assets/472589/15579918/9ac43af2-235e-11e6-8634-87ddd0077c1c.png)

This has been partially fixed at:
https://github.com/southlondonmakerspace/wordpress-theme/blob/master/static/less/post.less#L37-L40

Preview:
http://slms.wpengine.com/about/
