### ISSUE TITLE
Strange event padding under heading

### ISSUE THREAD

**Issue by unknowndomain** [southlondonmakerspace/wordpress-theme#25]
![screen shot 2016-06-18 at 20 19 17](https://cloud.githubusercontent.com/assets/147143/16173229/8f5f4a80-3592-11e6-97e2-6d1150adea56.PNG)

**Comment by thisislawatts** [comment]
![updatedheaderspacing](https://cloud.githubusercontent.com/assets/472589/17037487/1aa5075a-4f89-11e6-90de-bdc9575d2090.png)
