### ISSUE TITLE
South London Maker Festival - Workshop tickets

### ISSUE THREAD

**Issue by Freddrin** [southlondonmakerspace/wordpress-theme#26]
Hi, 

I am interested in booking tickets for the longer workshops running at the South London Maker Festival however i cant find any information on where to purchase the tickets other than a line which reads 'booking details will be posted shortly…' however i imagine the tickets should be lice now given the even is less than a week away?

Likewise I imagine there would be a comment stating that there are no further tickets available if this was the case so I'm guessing this may be an issue that has not been noticed until now! 

I hope this helps!

**Comment by Freddrin** [comment]
I found the correct link through eventbright however it was tough to find! 

Also it does appear that all the tickets are now sold out!

**Comment by dermot-jones** [comment]
Hi @Freddrin,

Thanks for flagging this - and apologies for the wild goose chase the links sent you on. I just tried it myself and it was very confusing...

[Eventbrite](https://www.eventbrite.co.uk/e/south-london-maker-festival-tickets-56274310979) listing should be all working and much clearer now, with the correct links

It's definitely worth putting you name on the wait list for any sold out workshops that interest you, and also making your interest known when you arrive on the day as there may be returns -  and any unclaimed tickets will be released 20 minutes before the start of each workshop 

Was there a particular workshop you were interested in?

**Comment by Freddrin** [comment]
Hi,

I’ll put myself on the waiting list for sure! I was keen to have a go at the ring making however I’ve signed up for the coin cutting instead as this also seems super interesting! 

I’m looking forward to Saturday! 

Kind regards,
Freddie

**Comment by dermot-jones** [comment]
Hi Freddie,

Yes, the ring making sold out very quickly

See you on Saturday

Best,

Dermot

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
