### ISSUE TITLE
Mega Footer

### ISSUE THREAD

**Issue by thisislawatts** [southlondonmakerspace/wordpress-theme#5]
The latest version of the template is available to preview at: 
http://slms.wpengine.com

Do we need to add a large footer to accommodate the various sponsor bits and pieces
![screenshot 2016-05-24 at 22 55 54](https://cloud.githubusercontent.com/assets/472589/15521331/1b18f4b6-2203-11e6-9ce6-705a608b3154.png)

**Comment by unknowndomain** [comment]
This was an unresolved issue in the design... It could just be more widgets like Tom did for the old site...

I only proposed this before...

![screen shot 2016-05-25 at 00 34 43](https://cloud.githubusercontent.com/assets/147143/15523183/8ba1a450-2210-11e6-978d-d9a42309c057.PNG)

![screen shot 2016-05-25 at 00 34 09](https://cloud.githubusercontent.com/assets/147143/15523172/72dcbc0c-2210-11e6-8846-b86201fd9466.PNG)

**Comment by thisislawatts** [comment]
OK not a problem we can definitely sort something out for this

**Comment by Tomnewsom** [comment]
We need to include the Mayor of London in there somewhere (can't find where to edit the footer in the wp interface)

**Comment by thisislawatts** [comment]
The Sponsors footer is currently pulling it's content from the Sponsor page
so can be edited there
