### ISSUE TITLE
Map should be a Makerspace logo icon like Open Workshop Network

### ISSUE THREAD

**Issue by unknowndomain** [southlondonmakerspace/wordpress-theme#7]
![screen shot 2016-05-25 at 00 37 36](https://cloud.githubusercontent.com/assets/147143/15523253/0ea71eb6-2211-11e6-9ceb-9fbb4aa1c1bd.PNG)

**Comment by thisislawatts** [comment]
![screenshot 2016-05-25 at 10 02 04](https://cloud.githubusercontent.com/assets/472589/15534421/9a705d8c-2260-11e6-8eb0-8b92b7ca4591.png)

I think that this might make for too many M's and we're better off with a simple marker.

**Comment by unknowndomain** [comment]
[logo pixelgrid copy.svg.zip](https://github.com/southlondonmakerspace/wordpress-theme/files/282428/logo.pixelgrid.copy.svg.zip)
